CREATE TABLE IF NOT EXISTS "letter_template_sentences" (
  "id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "key" varchar NOT NULL,
  "category" varchar NOT NULL,
  "label" varchar NOT NULL,
  "sentence" text NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(),
  CONSTRAINT "uq_letter_template_key_category" UNIQUE ("key", "category")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "role_summary_templates" (
  "id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "role_key" varchar NOT NULL UNIQUE,
  "role_family" varchar NOT NULL,
  "vertical" varchar NOT NULL,
  "level" varchar NOT NULL,
  "role_label" varchar NOT NULL,
  "default_summary" text NOT NULL,
  "alternate_summary" text NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp DEFAULT now()
);

--> statement-breakpoint
INSERT INTO "letter_template_sentences" ("id","key","category","label","sentence","sort_order") VALUES
  (gen_random_uuid(),'factual_only','performance_band','Factual Only','During the above tenure, the employee was associated with the organization in the stated role and department.',1),
  (gen_random_uuid(),'standard','performance_band','Standard','During the tenure, the employee carried out assigned responsibilities in a satisfactory manner.',2),
  (gen_random_uuid(),'good','performance_band','Good','During the tenure, the employee demonstrated diligence and responsibility in assigned work.',3),
  (gen_random_uuid(),'very_good','performance_band','Very Good','During the tenure, the employee demonstrated professionalism, commitment, and good execution of assigned responsibilities.',4),
  (gen_random_uuid(),'excellent','performance_band','Excellent','During the tenure, the employee demonstrated a high level of professionalism, ownership, and effectiveness in assigned responsibilities.',5),
  (gen_random_uuid(),'standard','conduct_band','Satisfactory','Professional conduct during the tenure was satisfactory.',1),
  (gen_random_uuid(),'good','conduct_band','Good','Professional conduct during the tenure was good.',2),
  (gen_random_uuid(),'very_good','conduct_band','Very Good','Professional conduct during the tenure was very good.',3),
  (gen_random_uuid(),'successfully_completed','completion_band','Successfully Completed','successfully completed',1),
  (gen_random_uuid(),'completed','completion_band','Completed','completed',2),
  (gen_random_uuid(),'served_during_period','completion_band','Served During the Period','served during the period',3),
  (gen_random_uuid(),'wish_success','closing_line','Wish Success','We wish him/her all the best in future endeavours.',1),
  (gen_random_uuid(),'wish_career','closing_line','Wish Career','We wish him/her continued success in their career.',2),
  (gen_random_uuid(),'wish_professional','closing_line','Wish Professional','We wish him/her the very best in all future professional pursuits.',3)
ON CONFLICT ON CONSTRAINT "uq_letter_template_key_category" DO NOTHING;

--> statement-breakpoint
INSERT INTO "role_summary_templates" ("id","role_key","role_family","vertical","level","role_label","default_summary","alternate_summary","sort_order") VALUES
  (gen_random_uuid(),'hc_sourcer_intern','sourcing','healthcare','intern','Healthcare Sourcer - Intern','Supported sourcing activities for healthcare positions by identifying potential candidates, screening basic profile fit, maintaining candidate records, and assisting the recruitment team with pipeline updates and follow-ups.','Assisted in talent sourcing for healthcare roles through profile review, candidate outreach support, database maintenance, and coordination of candidate information for the recruiting team.',10),
  (gen_random_uuid(),'hc_sourcer_senior','sourcing','healthcare','senior','Healthcare Sourcer - Senior','Handled sourcing for healthcare positions by building candidate pipelines, identifying qualified professionals, conducting initial profile assessments, maintaining sourcing trackers, and supporting timely submission readiness.','Managed targeted sourcing for healthcare requirements through market mapping, resume screening, candidate outreach, database organization, and ongoing pipeline support aligned with business priorities.',20),
  (gen_random_uuid(),'hc_sourcer_lead','sourcing','healthcare','lead','Healthcare Sourcer - Lead','Led healthcare sourcing activities by driving candidate pipeline generation, guiding sourcing priorities, supporting team coordination, maintaining sourcing quality standards, and enabling recruiters with qualified candidate flow.','Oversaw sourcing execution for healthcare roles through pipeline planning, profile quality checks, team guidance, sourcing process improvement, and support for timely recruitment delivery.',30),
  (gen_random_uuid(),'hc_recruiter_intern','recruiting','healthcare','intern','Healthcare Recruiter - Intern','Supported healthcare recruitment activities by assisting with candidate sourcing, screening coordination, interview scheduling, database updates, and follow-up communication throughout the hiring process.','Assisted the recruitment team in handling healthcare hiring tasks including candidate coordination, basic profile review, scheduling support, and maintaining recruitment records and status updates.',40),
  (gen_random_uuid(),'hc_recruiter_senior','recruiting','healthcare','senior','Healthcare Recruiter - Senior','Managed end-to-end recruitment for healthcare positions including candidate sourcing, screening, interview coordination, submission management, offer follow-up, and stakeholder communication.','Handled full-cycle healthcare recruitment by identifying suitable candidates, evaluating profile fit, coordinating interviews, maintaining candidate engagement, and supporting closure of open requirements.',50),
  (gen_random_uuid(),'hc_recruiter_lead','recruiting','healthcare','lead','Healthcare Recruiter - Lead','Led healthcare recruitment delivery by managing critical requirements, supporting team members, driving submission quality, coordinating hiring activities, and ensuring timely follow-up across the recruitment lifecycle.','Oversaw recruitment execution for healthcare roles through candidate pipeline management, screening oversight, recruiter guidance, process coordination, and focus on quality and turnaround timelines.',60),
  (gen_random_uuid(),'hc_recruiter_manager','recruiting','healthcare','manager','Healthcare Recruiter - Manager','Managed healthcare recruitment operations by overseeing team performance, monitoring hiring pipelines, supporting delivery planning, coordinating with stakeholders, and ensuring process discipline, quality, and target achievement.','Led the healthcare recruitment function through team supervision, workload planning, escalation handling, performance monitoring, and alignment of hiring delivery with business and client requirements.',70),
  (gen_random_uuid(),'it_sourcer_intern','sourcing','it','intern','IT Sourcer - Intern','Supported IT sourcing activities by researching candidate profiles, assisting with outreach, maintaining sourcing databases, and coordinating candidate information for the recruitment team.','Assisted in talent sourcing for IT roles through profile identification, outreach support, tracker maintenance, and pipeline updates for the recruiting team.',80),
  (gen_random_uuid(),'it_sourcer_senior','sourcing','it','senior','IT Sourcer - Senior','Handled targeted sourcing for IT positions by building qualified candidate pipelines, conducting profile assessments, maintaining sourcing trackers, and supporting recruitment team with timely candidate flow.','Managed IT sourcing efforts through market mapping, resume screening, candidate outreach, and database management aligned with open technical requirements.',90),
  (gen_random_uuid(),'it_sourcer_lead','sourcing','it','lead','IT Sourcer - Lead','Led IT sourcing activities by guiding pipeline generation, maintaining sourcing quality, coordinating team efforts, and ensuring recruiter-ready candidate flow across technical positions.','Oversaw IT sourcing execution through pipeline planning, profile quality reviews, team coordination, and continuous improvement of sourcing processes.',100),
  (gen_random_uuid(),'it_recruiter_intern','recruiting','it','intern','IT Recruiter - Intern','Supported IT recruitment activities by assisting with candidate sourcing, basic profile screening, interview coordination, applicant tracking updates, and follow-up communication during the hiring process.','Assisted the recruitment team in IT hiring operations through profile review support, candidate coordination, scheduling assistance, tracker maintenance, and timely status updates.',110),
  (gen_random_uuid(),'it_recruiter_senior','recruiting','it','senior','IT Recruiter - Senior','Managed end-to-end recruitment for IT positions including sourcing, screening, candidate evaluation, interview coordination, submission handling, and offer-stage follow-up.','Handled full-cycle IT recruitment by identifying qualified candidates, assessing technical profile alignment, coordinating interviews, maintaining candidate engagement, and supporting hiring closures.',120),
  (gen_random_uuid(),'it_recruiter_lead','recruiting','it','lead','IT Recruiter - Lead','Led IT recruitment delivery by managing priority requirements, guiding recruiters, improving submission quality, coordinating hiring workflows, and ensuring timely progress across open positions.','Oversaw recruitment execution for IT roles through team support, candidate pipeline management, screening oversight, process improvement, and delivery alignment with hiring goals.',130),
  (gen_random_uuid(),'it_recruiter_manager','recruiting','it','manager','IT Recruiter - Manager','Managed IT recruitment operations by supervising team performance, planning hiring delivery, monitoring open positions, supporting stakeholder communication, and ensuring quality, compliance, and target achievement.','Led the IT recruitment function through team management, process oversight, escalation resolution, hiring pipeline monitoring, and alignment of recruitment outcomes with business needs.',140),
  (gen_random_uuid(),'am_intern','account_management','all','intern','Account Manager - Intern','Supported client account management activities by assisting with client communication, maintaining account records, coordinating service delivery updates, and supporting the account team with data organization and follow-ups.','Assisted in account management functions by preparing client reports, tracking delivery milestones, organizing meeting notes, and supporting team members in client coordination activities.',150),
  (gen_random_uuid(),'am_senior','account_management','all','senior','Account Manager - Senior','Managed assigned client accounts by handling day-to-day communication, monitoring service delivery, coordinating with internal teams, addressing client queries, and supporting retention and satisfaction objectives.','Handled client relationship management for assigned accounts through regular engagement, delivery tracking, escalation coordination, and proactive communication on service updates and timelines.',160),
  (gen_random_uuid(),'am_lead','account_management','all','lead','Account Manager - Lead','Led account management for key clients by driving engagement strategies, overseeing delivery commitments, guiding junior account managers, and ensuring client satisfaction and long-term relationship growth.','Oversaw client account portfolios through senior relationship management, delivery oversight, issue resolution, team coordination, and alignment of service outcomes with client expectations.',170),
  (gen_random_uuid(),'am_manager','account_management','all','manager','Account Manager - Manager','Managed the account management function by overseeing client relationships across the portfolio, driving retention and growth, coordinating cross-functional delivery, and reporting on account health and performance.','Led client account management operations through strategic engagement, team supervision, escalation handling, and alignment of service delivery with commercial and client satisfaction goals.',180),
  (gen_random_uuid(),'delivery_intern','delivery','all','intern','Delivery Executive - Intern','Supported delivery operations by tracking assignment statuses, coordinating with recruitment teams, maintaining delivery records, and assisting with reporting and candidate follow-up activities.','Assisted delivery team with placement coordination, data maintenance, status tracking, and communication support for open positions and candidate submissions.',190),
  (gen_random_uuid(),'delivery_senior','delivery','all','senior','Delivery Executive - Senior','Managed delivery execution for assigned client requirements by tracking submission pipelines, coordinating candidate flow, managing timelines, and ensuring placement targets are met with quality standards.','Handled end-to-end delivery coordination for open positions including candidate tracking, submission oversight, placement follow-up, and alignment of delivery outcomes with client expectations.',200),
  (gen_random_uuid(),'delivery_lead','delivery','all','lead','Delivery Manager - Lead','Led delivery operations by overseeing submission quality, coordinating team delivery efforts, managing client timelines, and driving consistent placement outcomes across active requirements.','Oversaw recruitment delivery by guiding team members, monitoring pipeline health, resolving delivery bottlenecks, and ensuring alignment with client hiring targets.',210),
  (gen_random_uuid(),'delivery_manager','delivery','all','manager','Delivery Manager','Managed the delivery function by supervising team performance, planning capacity across open requirements, coordinating with account and recruitment teams, and ensuring consistent and quality-driven placement outcomes.','Led delivery management operations through team oversight, workload planning, performance monitoring, and strategic alignment of recruitment capacity with client delivery expectations.',220),
  (gen_random_uuid(),'ops_intern','operations','all','intern','Operations Executive - Intern','Supported operational processes by assisting with data management, process documentation, coordination tasks, and administrative activities across HR and business operations functions.','Assisted operations team with data entry, record maintenance, process support, and coordination of internal administrative activities.',230),
  (gen_random_uuid(),'ops_senior','operations','all','senior','Operations Executive - Senior','Handled operational responsibilities including process management, data quality oversight, coordination with cross-functional teams, compliance tracking, and support for operational reporting and analysis.','Managed day-to-day operational activities including process execution, data management, team coordination, and support for operational efficiency and reporting initiatives.',240),
  (gen_random_uuid(),'ops_lead','operations','all','lead','Operations Lead','Led operations activities by overseeing process execution, guiding team members, managing operational reporting, and ensuring efficiency, compliance, and quality across organizational workflows.','Oversaw operational functions through process oversight, team coordination, performance monitoring, and continuous improvement of internal workflows and administrative processes.',250),
  (gen_random_uuid(),'ops_manager','operations','all','manager','Operations Manager','Managed business operations by overseeing process design and execution, leading the operations team, driving operational improvements, and aligning function activities with organizational goals.','Led the operations function through team management, process governance, performance tracking, and strategic alignment of operational activities with business requirements.',260),
  (gen_random_uuid(),'bd_intern','business_development','all','intern','Business Development Executive - Intern','Supported business development activities by researching prospective clients, maintaining CRM records, assisting with outreach coordination, and supporting the BD team with pitch preparation and follow-up activities.','Assisted the business development team with market research, lead tracking, meeting coordination, and preparation of sales materials for client engagement.',270),
  (gen_random_uuid(),'bd_senior','business_development','all','senior','Business Development Executive - Senior','Managed business development activities by identifying new client opportunities, conducting outreach, maintaining prospect pipelines, coordinating introductory meetings, and supporting contract initiation processes.','Handled client acquisition activities including lead generation, prospect engagement, pitch coordination, and CRM management for new business opportunities.',280),
  (gen_random_uuid(),'bd_manager','business_development','all','manager','Business Development Manager','Led business development efforts by building and managing client pipelines, overseeing the BD team, driving new account acquisition, and aligning commercial strategies with organizational growth targets.','Managed the business development function through team leadership, market development, strategic client engagement, and coordination of revenue growth activities.',290),
  (gen_random_uuid(),'director','leadership','all','director','Director','Provided strategic direction and operational leadership across assigned business functions, managing senior teams, driving growth initiatives, overseeing key client relationships, and ensuring alignment with organizational objectives.','Led organizational functions at a senior level through strategic planning, team development, stakeholder management, and execution of business priorities aligned with company goals.',300),
  (gen_random_uuid(),'vp_bd','leadership','all','vp','VP - Business Development','Led the business development function at an organizational level by setting commercial strategy, managing BD leadership, driving new revenue streams, and building high-value client partnerships.','Drove organizational growth through executive-level business development strategy, senior stakeholder engagement, market expansion initiatives, and leadership of the commercial team.',310),
  (gen_random_uuid(),'country_head','leadership','all','country_head','Country Head','Provided executive leadership for country-level operations by overseeing all business functions, managing senior leadership teams, driving strategic growth, and representing the organization to clients and stakeholders.','Led all organizational functions within the country through executive management, strategic planning, client relationship stewardship, and cross-functional leadership.',320)
ON CONFLICT ("role_key") DO NOTHING;
