-- Task #336 follow-up: switch the seeded performance clauses to fragment-based
-- optional wording ({{ ... }}) so that omitting the optional ceiling no longer
-- deletes mandatory legal text. Only rows still holding the original 0015 seed
-- text are updated, preserving any Admin/Super-Admin edits.
UPDATE "letter_template_sentences"
SET "sentence" = E'Your compensation during the initial probation period will be ₹[ProbationSalary] per month. The initial probation period will be [ProbationMonths] from your date of joining.\n\nUpon completion of the initial probation period, the Company will conduct a performance and delivery review. Subject to your performance, achievement of assigned goals, quality of delivery, consistency, professional conduct, and overall contribution, your salary may be reconsidered.\n\nEmployees who meet the expected performance and delivery standards may continue at the existing compensation or may be considered for revision based on management''s assessment. {{Employees who significantly exceed the expected goals and demonstrate strong ownership, consistent delivery, and measurable business impact may be considered for a salary revision of up to ₹[MaxRevisionSalary] per month.}}\n\nAny salary revision will be at the sole discretion of the Company and will be confirmed separately in writing. Mention of the review amount does not create an automatic entitlement or guarantee of salary increase.{{ The Company may also extend the probation period up to [ExtendedProbationMonths], if required, based on performance, delivery, conduct, or business needs.}}'
WHERE "key" = 'probation_performance_review' AND "category" = 'offer_clause'
  AND "sentence" = E'Your compensation during the initial probation period will be ₹[ProbationSalary] per month. The initial probation period will be [ProbationMonths] from your date of joining.\n\nUpon completion of the initial probation period, the Company will conduct a performance and delivery review. Subject to your performance, achievement of assigned goals, quality of delivery, consistency, professional conduct, and overall contribution, your salary may be reconsidered.\n\nEmployees who meet the expected performance and delivery standards may continue at the existing compensation or may be considered for revision based on management''s assessment. Employees who significantly exceed the expected goals and demonstrate strong ownership, consistent delivery, and measurable business impact may be considered for a salary revision of up to ₹[MaxRevisionSalary] per month.\n\nAny salary revision will be at the sole discretion of the Company and will be confirmed separately in writing. Mention of the review amount does not create an automatic entitlement or guarantee of salary increase.\nThe Company may also extend the probation period up to [ExtendedProbationMonths], if required, based on performance, delivery, conduct, or business needs.';
--> statement-breakpoint
UPDATE "letter_template_sentences"
SET "sentence" = E'Your current salary is ₹[CurrentSalary] per month. As discussed, a 90-day performance plan with defined goals and targets has been agreed with you.\n\nAt the end of the 90-day period, your performance will be reviewed against the agreed goals and targets, productivity expectations, quality of submissions, successful delivery outcomes, compliance discipline, communication standards, ownership, and overall contribution to the Healthcare Recruitment department.\n\nBased on the outcome of this review:\n- If performance meets the agreed targets, the Company may continue the existing salary or consider a revision based on overall performance and business needs.\n- If performance significantly exceeds the agreed targets and demonstrates strong, measurable results, the Company may consider a salary revision of up to ₹[MaxRevisionSalary] per month.\n- If performance is below the agreed targets, the plan period may be extended or the arrangement reviewed further in accordance with your terms of employment.\n\nAny salary revision{{, including any increase up to ₹[MaxRevisionSalary] per month,}} shall not be automatic and will be subject to management review, business requirements, and written approval by the Company.'
WHERE "key" = 'growth_plan_review' AND "category" = 'addendum_clause'
  AND "sentence" = E'Your current salary is ₹[CurrentSalary] per month. As discussed, a 90-day performance plan with defined goals and targets has been agreed with you.\n\nAt the end of the 90-day period, your performance will be reviewed against the agreed goals and targets, productivity expectations, quality of submissions, successful delivery outcomes, compliance discipline, communication standards, ownership, and overall contribution to the Healthcare Recruitment department.\n\nBased on the outcome of this review:\n- If performance meets the agreed targets, the Company may continue the existing salary or consider a revision based on overall performance and business needs.\n- If performance significantly exceeds the agreed targets and demonstrates strong, measurable results, the Company may consider a salary revision of up to ₹[MaxRevisionSalary] per month.\n- If performance is below the agreed targets, the plan period may be extended or the arrangement reviewed further in accordance with your terms of employment.\n\nAny salary revision, including any increase up to ₹[MaxRevisionSalary] per month, shall not be automatic and will be subject to management review, business requirements, and written approval by the Company.';
