// Process Governance Center — 21-SOP Launch Library seed data (Task #660).
// Sourced from the Final SOP Launch Playbook (HIS-IMPL final library).
// IMPORTANT: plain ASCII only in every string (no Unicode dashes/symbols) to
// avoid ON CONFLICT mismatches on re-seed.
//
// audienceRoles holds SYSTEM role slugs (user_role enum) so the phased-rollout
// gate can match a user's role against a SOP's audience. launchWave 0 = always-on
// foundation/governance docs; waves 1-5 follow the playbook's successive rollout.

export interface SopRoleAssignmentSeed {
  role: string;
  trainingType: string;
  quizRequired: boolean;
  kpiDescription: string;
  auditOwnerRole: string;
  frequency: string;
  evidenceDescription: string;
  target: string;
}

export interface SopSeed {
  code: string;
  title: string;
  category: string;
  owner: string;
  approver: string;
  audienceRoles: string[];
  launchWave: number;
  reviewCycle: string;
  confidentiality: string;
  kpiDescription: string;
  auditOwnerRole: string;
  frequency: string;
  evidenceDescription: string;
  target: string;
  aiAssistAllowed: boolean;
  humanSignoffRequired: boolean;
  summary: string;
  roleAssignments: SopRoleAssignmentSeed[];
}

const REVIEW_CYCLE = "Quarterly for first 2 quarters, then semiannual";
const CONFIDENTIALITY = "Internal - Hire'in Solutions only";

export const SOP_SEED: SopSeed[] = [
  {
    code: "GOV-001",
    title: "SOP Governance, Document Control & Change Management",
    category: "Governance",
    owner: "CEO / Ops",
    approver: "Leadership",
    audienceRoles: ["super_admin", "admin", "hr", "operations", "manager"],
    launchWave: 0,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "SOP review completion, change log compliance",
    auditOwnerRole: "Ops",
    frequency: "Monthly during rollout",
    evidenceDescription: "Approved SOP index, change log, acknowledgments",
    target: "100% docs controlled",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "How SOPs are owned, versioned, approved, and changed. Every SOP has an owner, evidence requirement, quality gate, and audit cadence.",
    roleAssignments: [
      { role: "manager", trainingType: "Manager orientation", quizRequired: true, kpiDescription: "SOP review completion, change log compliance", auditOwnerRole: "Ops", frequency: "Monthly during rollout", evidenceDescription: "Approved SOP index, change log, acknowledgments", target: "100% docs controlled" },
      { role: "operations", trainingType: "Manager orientation", quizRequired: true, kpiDescription: "SOP review completion, change log compliance", auditOwnerRole: "Ops", frequency: "Monthly during rollout", evidenceDescription: "Approved SOP index, change log, acknowledgments", target: "100% docs controlled" },
      { role: "hr", trainingType: "Manager orientation", quizRequired: true, kpiDescription: "SOP review completion, change log compliance", auditOwnerRole: "Ops", frequency: "Monthly during rollout", evidenceDescription: "Approved SOP index, change log, acknowledgments", target: "100% docs controlled" },
    ],
  },
  {
    code: "REQ-001",
    title: "Requirement Synthesis & Intake Calibration",
    category: "Talent Acquisition",
    owner: "TA Delivery Manager",
    approver: "CEO / Sales Director",
    audienceRoles: ["recruiter", "manager"],
    launchWave: 1,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Requirement clarity score, calibration completeness",
    auditOwnerRole: "Delivery Manager",
    frequency: "Weekly",
    evidenceDescription: "Calibrated requirement brief, must-have/nice-to-have split",
    target: "95%+ calibrated before sourcing",
    aiAssistAllowed: true,
    humanSignoffRequired: true,
    summary: "Turn raw client requirements into a calibrated, must-have-driven brief before any sourcing begins. AI may draft the synthesis; a human must sign off.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Live workshop + role play", quizRequired: true, kpiDescription: "Requirement clarity score, calibration completeness", auditOwnerRole: "Delivery Manager", frequency: "Weekly", evidenceDescription: "Calibrated requirement brief, must-have split", target: "95%+ calibrated before sourcing" },
      { role: "manager", trainingType: "Live workshop + role play", quizRequired: true, kpiDescription: "Requirement clarity score, calibration completeness", auditOwnerRole: "Delivery Manager", frequency: "Weekly", evidenceDescription: "Calibrated requirement brief, must-have split", target: "95%+ calibrated before sourcing" },
    ],
  },
  {
    code: "TA-001",
    title: "Requisition Intake, Rate Alignment & Delivery Kickoff",
    category: "Talent Acquisition",
    owner: "TA Delivery Manager",
    approver: "CEO / Sales Director",
    audienceRoles: ["recruiter", "manager"],
    launchWave: 1,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Intake completeness, rate approval, role release readiness",
    auditOwnerRole: "Delivery Manager",
    frequency: "Weekly",
    evidenceDescription: "Intake notes, rate sheet, assignment board",
    target: "95%+ complete",
    aiAssistAllowed: true,
    humanSignoffRequired: true,
    summary: "Requirement intake, must-haves, pay/bill rate alignment, and a clean delivery kickoff so recruiters start on accurate, approved roles.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Live workshop + role play", quizRequired: true, kpiDescription: "Intake completeness, rate approval, role release readiness", auditOwnerRole: "Delivery Manager", frequency: "Weekly", evidenceDescription: "Intake notes, rate sheet, assignment board", target: "95%+ complete" },
      { role: "manager", trainingType: "Live workshop + role play", quizRequired: true, kpiDescription: "Intake completeness, rate approval, role release readiness", auditOwnerRole: "Delivery Manager", frequency: "Weekly", evidenceDescription: "Intake notes, rate sheet, assignment board", target: "95%+ complete" },
    ],
  },
  {
    code: "TA-002",
    title: "Sourcing, Outreach, Candidate Ownership & Consent",
    category: "Talent Acquisition",
    owner: "TA Delivery Manager",
    approver: "CEO / HR",
    audienceRoles: ["recruiter", "manager"],
    launchWave: 2,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Candidate ownership logs, duplicate avoidance, outreach quality",
    auditOwnerRole: "Lead Recruiter",
    frequency: "Weekly",
    evidenceDescription: "ATS notes, candidate consent record",
    target: "100% consent where required",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "Sourcing tools, ethical outreach, candidate ownership rules, and consent/RTR capture. Work must be visible in the ATS, not in personal messages.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Live workshop", quizRequired: true, kpiDescription: "Candidate ownership logs, duplicate avoidance, outreach quality", auditOwnerRole: "Lead Recruiter", frequency: "Weekly", evidenceDescription: "ATS notes, candidate consent record", target: "100% consent where required" },
      { role: "manager", trainingType: "Live workshop", quizRequired: true, kpiDescription: "Candidate ownership logs, duplicate avoidance, outreach quality", auditOwnerRole: "Lead Recruiter", frequency: "Weekly", evidenceDescription: "ATS notes, candidate consent record", target: "100% consent where required" },
    ],
  },
  {
    code: "TA-003",
    title: "Screening, Qualification & Submission Quality Control",
    category: "Talent Acquisition",
    owner: "TA Delivery Manager",
    approver: "CEO / Compliance",
    audienceRoles: ["recruiter", "manager"],
    launchWave: 1,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Submission acceptance rate, rework rate, interview conversion",
    auditOwnerRole: "Lead / AM",
    frequency: "Weekly",
    evidenceDescription: "Submission packet, QC checklist",
    target: "95%+ QC pass",
    aiAssistAllowed: true,
    humanSignoffRequired: true,
    summary: "Screening, qualification, the submission checklist, and the QC gate. Submissions count only when qualified, documented, and aligned to the requirement.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Workshop + submission audit", quizRequired: true, kpiDescription: "Submission acceptance rate, rework rate, interview conversion", auditOwnerRole: "Lead / AM", frequency: "Weekly", evidenceDescription: "Submission packet, QC checklist", target: "95%+ QC pass" },
      { role: "manager", trainingType: "Workshop + submission audit", quizRequired: true, kpiDescription: "Submission acceptance rate, rework rate, interview conversion", auditOwnerRole: "Lead / AM", frequency: "Weekly", evidenceDescription: "Submission packet, QC checklist", target: "95%+ QC pass" },
    ],
  },
  {
    code: "TA-004",
    title: "Interview, Offer, Start & Retention Follow-Through",
    category: "Talent Acquisition",
    owner: "TA Delivery Manager",
    approver: "CEO / Sales Director",
    audienceRoles: ["recruiter", "manager"],
    launchWave: 2,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Interview show rate, offer-to-start, start retention",
    auditOwnerRole: "AM / Delivery Manager",
    frequency: "Weekly",
    evidenceDescription: "Interview tracker, offer notes, start confirmation",
    target: "90%+ show rate",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "Interview scheduling, offer management, start tracking, and post-start retention follow-through to protect interview-to-start conversion.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Scenario training", quizRequired: true, kpiDescription: "Interview show rate, offer-to-start, start retention", auditOwnerRole: "AM / Delivery Manager", frequency: "Weekly", evidenceDescription: "Interview tracker, offer notes, start confirmation", target: "90%+ show rate" },
      { role: "manager", trainingType: "Scenario training", quizRequired: true, kpiDescription: "Interview show rate, offer-to-start, start retention", auditOwnerRole: "AM / Delivery Manager", frequency: "Weekly", evidenceDescription: "Interview tracker, offer notes, start confirmation", target: "90%+ show rate" },
    ],
  },
  {
    code: "HC-001",
    title: "Healthcare Credential Packet & Compliance Readiness",
    category: "Healthcare",
    owner: "Healthcare Manager",
    approver: "CEO / Compliance",
    audienceRoles: ["recruiter", "operations", "hr"],
    launchWave: 3,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Credential packet completeness, expiration tracking",
    auditOwnerRole: "Healthcare Manager / Ops",
    frequency: "Weekly",
    evidenceDescription: "Credential packet, verification notes",
    target: "100% required docs",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "Credential-aware screening, license/cert checks, packet handoff, and audit readiness for healthcare placements.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Compliance lab", quizRequired: true, kpiDescription: "Credential packet completeness, expiration tracking", auditOwnerRole: "Healthcare Manager / Ops", frequency: "Weekly", evidenceDescription: "Credential packet, verification notes", target: "100% required docs" },
      { role: "operations", trainingType: "Compliance lab", quizRequired: true, kpiDescription: "Credential packet completeness, expiration tracking", auditOwnerRole: "Healthcare Manager / Ops", frequency: "Weekly", evidenceDescription: "Credential packet, verification notes", target: "100% required docs" },
      { role: "hr", trainingType: "Compliance lab", quizRequired: true, kpiDescription: "Credential packet completeness, expiration tracking", auditOwnerRole: "Healthcare Manager / Ops", frequency: "Weekly", evidenceDescription: "Credential packet, verification notes", target: "100% required docs" },
    ],
  },
  {
    code: "IT-001",
    title: "IT Staffing Delivery, Technical Screening & Submission Governance",
    category: "IT",
    owner: "IT Delivery Manager",
    approver: "CEO / Sales Director",
    audienceRoles: ["recruiter", "manager"],
    launchWave: 2,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Submittal quality, interview ratio, margin guardrail",
    auditOwnerRole: "IT Delivery Manager",
    frequency: "Weekly",
    evidenceDescription: "ATS submission notes, tech screen summary",
    target: "95%+ complete",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "IT requirement calibration, technical screening, visa/work authorization handling, and submission standards for IT staffing.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Functional training", quizRequired: true, kpiDescription: "Submittal quality, interview ratio, margin guardrail", auditOwnerRole: "IT Delivery Manager", frequency: "Weekly", evidenceDescription: "ATS submission notes, tech screen summary", target: "95%+ complete" },
      { role: "manager", trainingType: "Functional training", quizRequired: true, kpiDescription: "Submittal quality, interview ratio, margin guardrail", auditOwnerRole: "IT Delivery Manager", frequency: "Weekly", evidenceDescription: "ATS submission notes, tech screen summary", target: "95%+ complete" },
    ],
  },
  {
    code: "ENG-001",
    title: "Engineering & Professional Services Delivery Standards",
    category: "Engineering",
    owner: "Engineering Delivery Manager",
    approver: "CEO / Sales Director",
    audienceRoles: ["recruiter", "manager"],
    launchWave: 3,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Submittal quality, domain screening accuracy, interview conversion",
    auditOwnerRole: "Delivery Manager",
    frequency: "Weekly",
    evidenceDescription: "ATS submission notes, domain screen summary",
    target: "95%+ complete",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "Requirement calibration, domain-aware screening, and submission standards for engineering and professional services placements.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Functional training", quizRequired: true, kpiDescription: "Submittal quality, domain screening accuracy, interview conversion", auditOwnerRole: "Delivery Manager", frequency: "Weekly", evidenceDescription: "ATS submission notes, domain screen summary", target: "95%+ complete" },
      { role: "manager", trainingType: "Functional training", quizRequired: true, kpiDescription: "Submittal quality, domain screening accuracy, interview conversion", auditOwnerRole: "Delivery Manager", frequency: "Weekly", evidenceDescription: "ATS submission notes, domain screen summary", target: "95%+ complete" },
    ],
  },
  {
    code: "SALES-001",
    title: "Client, MSP/VMS, Rate Governance & Escalation",
    category: "Sales",
    owner: "Sales Director",
    approver: "CEO",
    audienceRoles: ["manager", "admin"],
    launchWave: 1,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Client cadence, status update timeliness, margin review",
    auditOwnerRole: "Sales Director",
    frequency: "Weekly",
    evidenceDescription: "Client update log, VMS status, escalation log",
    target: "95%+ status accuracy",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "Client and MSP/VMS communication, rate governance, SLA management, and escalation handling.",
    roleAssignments: [
      { role: "manager", trainingType: "Manager workshop", quizRequired: true, kpiDescription: "Client cadence, status update timeliness, margin review", auditOwnerRole: "Sales Director", frequency: "Weekly", evidenceDescription: "Client update log, VMS status, escalation log", target: "95%+ status accuracy" },
      { role: "admin", trainingType: "Manager workshop", quizRequired: true, kpiDescription: "Client cadence, status update timeliness, margin review", auditOwnerRole: "Sales Director", frequency: "Weekly", evidenceDescription: "Client update log, VMS status, escalation log", target: "95%+ status accuracy" },
    ],
  },
  {
    code: "BD-001",
    title: "Business Development, Lead Qualification & Client Onboarding",
    category: "Business Development",
    owner: "BD Manager",
    approver: "CEO / Sales Director",
    audienceRoles: ["manager", "admin"],
    launchWave: 4,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Qualified lead rate, onboarding completeness, conversion",
    auditOwnerRole: "Sales Director",
    frequency: "Weekly",
    evidenceDescription: "Lead qualification notes, onboarding checklist",
    target: "90%+ onboarding complete",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "Lead qualification, opportunity vetting, and structured client onboarding so new accounts start with clear terms and ownership.",
    roleAssignments: [
      { role: "manager", trainingType: "Manager workshop", quizRequired: true, kpiDescription: "Qualified lead rate, onboarding completeness, conversion", auditOwnerRole: "Sales Director", frequency: "Weekly", evidenceDescription: "Lead qualification notes, onboarding checklist", target: "90%+ onboarding complete" },
      { role: "admin", trainingType: "Manager workshop", quizRequired: true, kpiDescription: "Qualified lead rate, onboarding completeness, conversion", auditOwnerRole: "Sales Director", frequency: "Weekly", evidenceDescription: "Lead qualification notes, onboarding checklist", target: "90%+ onboarding complete" },
    ],
  },
  {
    code: "MKT-001",
    title: "Marketing, Employer Brand & Content Governance",
    category: "Marketing",
    owner: "Marketing Manager",
    approver: "CEO",
    audienceRoles: ["manager", "admin"],
    launchWave: 4,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Content approval compliance, brand consistency, claim safety",
    auditOwnerRole: "Marketing Manager",
    frequency: "Monthly",
    evidenceDescription: "Approved content log, brand checklist",
    target: "100% approved before publish",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "Employer brand, content review/approval, and claim-safety governance for marketing output and social channels.",
    roleAssignments: [
      { role: "manager", trainingType: "Workshop", quizRequired: true, kpiDescription: "Content approval compliance, brand consistency, claim safety", auditOwnerRole: "Marketing Manager", frequency: "Monthly", evidenceDescription: "Approved content log, brand checklist", target: "100% approved before publish" },
      { role: "admin", trainingType: "Workshop", quizRequired: true, kpiDescription: "Content approval compliance, brand consistency, claim safety", auditOwnerRole: "Marketing Manager", frequency: "Monthly", evidenceDescription: "Approved content log, brand checklist", target: "100% approved before publish" },
    ],
  },
  {
    code: "CX-001",
    title: "Candidate Experience & Communication SLA",
    category: "Candidate Experience",
    owner: "TA Delivery Manager",
    approver: "CEO / HR",
    audienceRoles: ["recruiter", "manager"],
    launchWave: 3,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Candidate communication SLA, response timeliness, NPS",
    auditOwnerRole: "Delivery Manager",
    frequency: "Weekly",
    evidenceDescription: "Communication log, SLA report",
    target: "95%+ within SLA",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "Candidate-first communication standards and response SLAs across the funnel, from first contact through post-placement.",
    roleAssignments: [
      { role: "recruiter", trainingType: "Workshop", quizRequired: true, kpiDescription: "Candidate communication SLA, response timeliness, NPS", auditOwnerRole: "Delivery Manager", frequency: "Weekly", evidenceDescription: "Communication log, SLA report", target: "95%+ within SLA" },
      { role: "manager", trainingType: "Workshop", quizRequired: true, kpiDescription: "Candidate communication SLA, response timeliness, NPS", auditOwnerRole: "Delivery Manager", frequency: "Weekly", evidenceDescription: "Communication log, SLA report", target: "95%+ within SLA" },
    ],
  },
  {
    code: "PLAT-001",
    title: "ProKred / KleriQ SaaS Platform Usage & Data Handling",
    category: "Platform",
    owner: "Operations",
    approver: "CEO / Ops",
    audienceRoles: ["employee", "recruiter", "manager", "operations", "hr", "finance"],
    launchWave: 5,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "ProKred adoption, data handling compliance",
    auditOwnerRole: "Ops",
    frequency: "Monthly",
    evidenceDescription: "Platform usage log, data handling acknowledgment",
    target: "Adoption per rollout plan",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "How Hire'in uses ProKred and KleriQ as separate SaaS platforms (pilot/design-partner tools), including correct data handling and confidentiality.",
    roleAssignments: [
      { role: "operations", trainingType: "Ops briefing", quizRequired: true, kpiDescription: "ProKred adoption, data handling compliance", auditOwnerRole: "Ops", frequency: "Monthly", evidenceDescription: "Platform usage log, data handling acknowledgment", target: "Adoption per rollout plan" },
      { role: "recruiter", trainingType: "Ops briefing", quizRequired: true, kpiDescription: "ProKred adoption, data handling compliance", auditOwnerRole: "Ops", frequency: "Monthly", evidenceDescription: "Platform usage log, data handling acknowledgment", target: "Adoption per rollout plan" },
      { role: "manager", trainingType: "Ops briefing", quizRequired: true, kpiDescription: "ProKred adoption, data handling compliance", auditOwnerRole: "Ops", frequency: "Monthly", evidenceDescription: "Platform usage log, data handling acknowledgment", target: "Adoption per rollout plan" },
    ],
  },
  {
    code: "LEGAL-001",
    title: "Legal, Contracts, Confidentiality & Compliance",
    category: "Legal",
    owner: "Legal / Compliance",
    approver: "CEO",
    audienceRoles: ["admin", "operations", "hr", "manager"],
    launchWave: 5,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Contract compliance, confidentiality adherence",
    auditOwnerRole: "Legal / Ops",
    frequency: "Monthly",
    evidenceDescription: "Signed contracts, confidentiality acknowledgments",
    target: "100% contracts compliant",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "Contract handling, confidentiality, and lawful-conduct compliance across client and candidate engagements.",
    roleAssignments: [
      { role: "admin", trainingType: "Compliance workshop", quizRequired: true, kpiDescription: "Contract compliance, confidentiality adherence", auditOwnerRole: "Legal / Ops", frequency: "Monthly", evidenceDescription: "Signed contracts, confidentiality acknowledgments", target: "100% contracts compliant" },
      { role: "operations", trainingType: "Compliance workshop", quizRequired: true, kpiDescription: "Contract compliance, confidentiality adherence", auditOwnerRole: "Legal / Ops", frequency: "Monthly", evidenceDescription: "Signed contracts, confidentiality acknowledgments", target: "100% contracts compliant" },
      { role: "hr", trainingType: "Compliance workshop", quizRequired: true, kpiDescription: "Contract compliance, confidentiality adherence", auditOwnerRole: "Legal / Ops", frequency: "Monthly", evidenceDescription: "Signed contracts, confidentiality acknowledgments", target: "100% contracts compliant" },
    ],
  },
  {
    code: "FIN-001",
    title: "Finance, Invoicing, Margin & Payment Controls",
    category: "Finance",
    owner: "Finance Manager",
    approver: "CEO",
    audienceRoles: ["finance", "admin", "operations"],
    launchWave: 4,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Invoice accuracy, margin compliance, payment timeliness",
    auditOwnerRole: "Finance / Ops",
    frequency: "Monthly",
    evidenceDescription: "Invoice records, margin report, payment log",
    target: "100% invoices accurate",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "Invoicing, margin controls, and payment governance so revenue is recognized accurately and margins are protected.",
    roleAssignments: [
      { role: "finance", trainingType: "Finance workshop", quizRequired: true, kpiDescription: "Invoice accuracy, margin compliance, payment timeliness", auditOwnerRole: "Finance / Ops", frequency: "Monthly", evidenceDescription: "Invoice records, margin report, payment log", target: "100% invoices accurate" },
      { role: "admin", trainingType: "Finance workshop", quizRequired: true, kpiDescription: "Invoice accuracy, margin compliance, payment timeliness", auditOwnerRole: "Finance / Ops", frequency: "Monthly", evidenceDescription: "Invoice records, margin report, payment log", target: "100% invoices accurate" },
    ],
  },
  {
    code: "OPS-001",
    title: "Tool Access, Credential Control & Deprovisioning",
    category: "Operations",
    owner: "Operations",
    approver: "CEO / HR",
    audienceRoles: ["employee", "recruiter", "manager", "operations", "hr", "finance"],
    launchWave: 1,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Access request approval, deprovisioning completion",
    auditOwnerRole: "Ops",
    frequency: "Weekly",
    evidenceDescription: "Access register, approval email/ticket",
    target: "100% approval before access",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "Tool request, access approval under least privilege, password reset, and timely deprovisioning when people change roles or leave.",
    roleAssignments: [
      { role: "operations", trainingType: "Ops briefing", quizRequired: true, kpiDescription: "Access request approval, deprovisioning completion", auditOwnerRole: "Ops", frequency: "Weekly", evidenceDescription: "Access register, approval email/ticket", target: "100% approval before access" },
      { role: "manager", trainingType: "Ops briefing", quizRequired: true, kpiDescription: "Access request approval, deprovisioning completion", auditOwnerRole: "Ops", frequency: "Weekly", evidenceDescription: "Access register, approval email/ticket", target: "100% approval before access" },
      { role: "employee", trainingType: "Ops briefing", quizRequired: true, kpiDescription: "Access request approval, deprovisioning completion", auditOwnerRole: "Ops", frequency: "Weekly", evidenceDescription: "Access register, approval email/ticket", target: "100% approval before access" },
    ],
  },
  {
    code: "HR-001",
    title: "Training, Acknowledgment, Goals & Performance Linkage",
    category: "HR",
    owner: "HR / Ops",
    approver: "CEO",
    audienceRoles: ["employee", "recruiter", "manager", "hr"],
    launchWave: 5,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Training completion, acknowledgment, coaching records",
    auditOwnerRole: "HR / Ops",
    frequency: "Weekly rollout; monthly after",
    evidenceDescription: "LMS/training record, signed acknowledgment",
    target: "100% completion",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "Training records, acknowledgments, role scorecards, and coaching/PIP linkage that tie SOP adoption to performance.",
    roleAssignments: [
      { role: "hr", trainingType: "HR manager training", quizRequired: true, kpiDescription: "Training completion, acknowledgment, coaching records", auditOwnerRole: "HR / Ops", frequency: "Weekly rollout; monthly after", evidenceDescription: "LMS/training record, signed acknowledgment", target: "100% completion" },
      { role: "manager", trainingType: "HR manager training", quizRequired: true, kpiDescription: "Training completion, acknowledgment, coaching records", auditOwnerRole: "HR / Ops", frequency: "Weekly rollout; monthly after", evidenceDescription: "LMS/training record, signed acknowledgment", target: "100% completion" },
      { role: "employee", trainingType: "HR manager training", quizRequired: true, kpiDescription: "Training completion, acknowledgment, coaching records", auditOwnerRole: "HR / Ops", frequency: "Weekly rollout; monthly after", evidenceDescription: "LMS/training record, signed acknowledgment", target: "100% completion" },
    ],
  },
  {
    code: "AUDIT-001",
    title: "KPI Dashboard, Weekly Audit & Monthly Business Review",
    category: "Audit",
    owner: "Ops / Delivery Leadership",
    approver: "CEO",
    audienceRoles: ["manager", "operations", "hr", "admin"],
    launchWave: 0,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Audit score, corrective action closure, KPI adoption",
    auditOwnerRole: "Ops / CEO",
    frequency: "Weekly + Monthly",
    evidenceDescription: "Audit sheet, scorecard, MBR deck",
    target: "90%+ audit score",
    aiAssistAllowed: false,
    humanSignoffRequired: true,
    summary: "Weekly SOP audits, the KPI dashboard, the monthly business review, and corrective-action tracking.",
    roleAssignments: [
      { role: "manager", trainingType: "Leadership workshop", quizRequired: true, kpiDescription: "Audit score, corrective action closure, KPI adoption", auditOwnerRole: "Ops / CEO", frequency: "Weekly + Monthly", evidenceDescription: "Audit sheet, scorecard, MBR deck", target: "90%+ audit score" },
      { role: "operations", trainingType: "Leadership workshop", quizRequired: true, kpiDescription: "Audit score, corrective action closure, KPI adoption", auditOwnerRole: "Ops / CEO", frequency: "Weekly + Monthly", evidenceDescription: "Audit sheet, scorecard, MBR deck", target: "90%+ audit score" },
    ],
  },
  {
    code: "TRAIN-001",
    title: "Role-Based Training Curriculum & Certification Plan",
    category: "Training",
    owner: "HR / Training Lead",
    approver: "CEO",
    audienceRoles: ["employee", "recruiter", "manager", "hr"],
    launchWave: 0,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Certification completion and behavior adoption",
    auditOwnerRole: "HR / Training Lead",
    frequency: "Weekly during rollout",
    evidenceDescription: "Attendance, quiz score, certification tracker",
    target: "90% quiz pass",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "Role-based curriculum, certification, quizzes, and live work-sample checks. No more than two operational SOPs trained per week.",
    roleAssignments: [
      { role: "hr", trainingType: "Training program", quizRequired: true, kpiDescription: "Certification completion and behavior adoption", auditOwnerRole: "HR / Training Lead", frequency: "Weekly during rollout", evidenceDescription: "Attendance, quiz score, certification tracker", target: "90% quiz pass" },
      { role: "manager", trainingType: "Training program", quizRequired: true, kpiDescription: "Certification completion and behavior adoption", auditOwnerRole: "HR / Training Lead", frequency: "Weekly during rollout", evidenceDescription: "Attendance, quiz score, certification tracker", target: "90% quiz pass" },
    ],
  },
  {
    code: "TPL-001",
    title: "Manager Acknowledgment, Audit Checklists & Field Templates",
    category: "Templates",
    owner: "Ops / HR",
    approver: "CEO",
    audienceRoles: ["manager", "operations"],
    launchWave: 0,
    reviewCycle: REVIEW_CYCLE,
    confidentiality: CONFIDENTIALITY,
    kpiDescription: "Template usage, consistent documentation",
    auditOwnerRole: "Ops",
    frequency: "Weekly",
    evidenceDescription: "Completed forms/checklists",
    target: "95% usage",
    aiAssistAllowed: true,
    humanSignoffRequired: false,
    summary: "Standardized manager acknowledgment forms, audit checklists, and field templates so documentation stays consistent.",
    roleAssignments: [
      { role: "manager", trainingType: "Manager walkthrough", quizRequired: false, kpiDescription: "Template usage, consistent documentation", auditOwnerRole: "Ops", frequency: "Weekly", evidenceDescription: "Completed forms/checklists", target: "95% usage" },
      { role: "operations", trainingType: "Manager walkthrough", quizRequired: false, kpiDescription: "Template usage, consistent documentation", auditOwnerRole: "Ops", frequency: "Weekly", evidenceDescription: "Completed forms/checklists", target: "95% usage" },
    ],
  },
];
