// ============================================================================
// Centralized Access Configuration (Phase 1)
// ----------------------------------------------------------------------------
// Single source of truth mapping each feature key -> the exact set of roles
// allowed to use it. Every server-side permission guard resolves its allowed
// roles through this registry via `resolveRoles` / `isRoleAllowed`.
//
// The registry is the SINGLE SOURCE OF TRUTH for static feature -> role access.
// Every server-side guard resolves its allowed roles through `resolveRoles`,
// which always reads from this registry (layered with the DB-driven live matrix
// in Phase 2). The role lists hard-coded at each call site are only a defensive
// seed/default used if a key is somehow absent from the registry — they are not
// a runtime fallback path. The registry value for each key equals the effective
// role set that the legacy code granted, so consolidating onto this single path
// is byte-for-byte access-preserving.
// ============================================================================

export type AccessRegistry = Record<string, string[]>;

// Initially generated by scripts/genAccessControl.mjs; newer modules (release
// notes, insights launch, travel, salary advances, help desk) are appended by
// hand. Values are the EXACT effective role sets (auto-grants already baked in).
// Keep entries in sync with scripts/verifyAccessParity.mjs (run it after edits).
export const ACCESS_REGISTRY: AccessRegistry = {
  "admin.announcements": ["super_admin", "admin", "hr"],
  "admin.announcements.recipientCount": ["super_admin", "admin", "hr"],
  "admin.announcements.sendEmail": ["super_admin", "admin", "hr"],
  "admin.applications": ["super_admin", "admin", "hr", "operations", "recruiter", "manager"],
  "admin.applications.retryCeipal": ["super_admin", "admin", "hr", "operations", "recruiter", "manager"],
  "admin.auditLogs": ["super_admin", "admin", "executive"],
  "admin.contacts": ["super_admin", "admin", "hr", "operations", "recruiter", "manager"],
  "admin.employees.dossier": ["super_admin", "admin", "hr", "executive"],
  "admin.jobs": ["super_admin", "admin", "operations", "recruiter", "manager"],
  "admin.jobs.bulkDelete": ["super_admin", "admin", "operations", "recruiter", "manager"],
  "admin.jobs.bulkUpdate": ["super_admin", "admin", "operations", "recruiter", "manager"],
  "admin.jobs.syncCeipal": ["super_admin", "admin", "operations", "recruiter", "manager"],
  "admin.jobs.upload": ["super_admin", "admin", "operations", "recruiter", "manager"],
  "admin.myTeam": ["super_admin", "admin", "hr", "operations", "manager"],
  "admin.myTeam.applyLeave": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.attendance": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.auditLog": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.details": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.emergencyContacts": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.leaves": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.members": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.profile": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.regionalHolidays": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.myTeam.tickets": ["super_admin", "admin", "hr", "manager", "operations"],
  "admin.offerLetters.countersign": ["super_admin", "admin", "hr"],
  "admin.users.bulkUpload": ["super_admin", "admin", "manager"],
  "admin.users.delete": ["super_admin", "admin"],
  "admin.users.employmentStatus": ["super_admin", "admin", "manager"],
  "admin.users.hierarchy": ["super_admin", "admin", "hr", "manager"],
  "admin.users.patch": ["super_admin", "admin", "manager", "hr"],
  "admin.users.post": ["super_admin", "admin", "manager", "hr"],
  "admin.users.resendInvite": ["super_admin", "admin", "manager"],
  "admin.users.restore": ["super_admin", "admin"],
  "auth.register": ["super_admin"],
  "auth.totp.adminReset": ["super_admin", "admin"],
  "auth.totp.disable": ["super_admin"],
  "companyProfile": ["super_admin", "admin"],
  "contracts.clients": ["super_admin", "admin", "hr", "operations"],
  "contracts.clients.status": ["super_admin", "admin", "hr", "operations"],
  "contracts.countersign": ["super_admin", "admin", "hr"],
  "contracts.dispatch": ["super_admin", "admin", "hr", "operations", "manager", "architect"],
  "contracts.dispatch.approve": ["super_admin", "admin", "architect"],
  "contracts.dispatch.reject": ["super_admin", "admin", "architect"],
  "contracts.import": ["super_admin", "admin", "hr", "operations", "manager"],
  "contracts.invoices": ["super_admin", "admin", "hr", "operations"],
  "contracts.patch": ["super_admin", "admin", "hr", "operations"],
  "contracts.post": ["super_admin", "admin", "hr", "operations", "manager"],
  "contracts.send": ["super_admin", "admin", "hr", "operations"],
  "contracts.templates": ["super_admin", "admin", "hr", "operations"],
  "departments.delete": ["super_admin", "admin"],
  "departments.patch": ["super_admin", "admin", "hr"],
  "departments.post": ["super_admin", "admin", "hr"],
  "hr.admin.salarySlip": ["super_admin", "admin", "hr", "finance", "executive"],
  "hr.admin.salarySlips": ["super_admin", "admin", "hr", "finance", "executive"],
  "hr.admin.shifts.gracePeriod": ["super_admin", "admin", "hr"],
  "hr.attendance": ["super_admin", "admin", "hr", "manager"],
  "hr.attendance.absentEmployees": ["super_admin", "admin", "hr"],
  "hr.attendance.adminCorrection": ["super_admin", "admin", "hr", "manager"],
  "hr.attendance.breaks.teamStatus": ["super_admin", "admin", "hr", "manager", "operations"],
  "hr.attendance.correctionsSummary": ["super_admin", "admin", "hr", "operations", "manager"],
  "hr.attendance.download": ["super_admin", "admin", "hr", "manager", "operations"],
  "hr.attendance.graceUsage": ["super_admin", "admin", "hr", "manager"],
  "hr.attendance.member.range": ["super_admin", "admin", "hr", "manager", "operations"],
  "hr.attendance.myTeam": ["super_admin", "admin", "hr", "manager", "operations"],
  "hr.attendance.myTeam.range": ["super_admin", "admin", "hr", "manager", "operations"],
  "hr.attendance.regularization.bulkApprove": ["super_admin", "admin", "hr", "manager"],
  "hr.attendance.regularization.bulkOverride": ["super_admin", "admin", "hr"],
  "hr.attendance.regularization.override": ["super_admin", "admin", "hr"],
  "hr.attendance.regularization.review": ["super_admin", "admin", "hr", "manager"],
  "hr.attendance.team": ["super_admin", "admin", "hr"],
  "hr.attendanceReport.access": ["super_admin", "admin", "hr", "executive"],
  "hr.attendanceReport.salaryGateStatus": ["super_admin", "admin", "hr"],
  "hr.checkIns": ["super_admin", "admin", "hr", "manager"],
  "hr.documentCompliance": ["super_admin", "admin", "hr", "executive"],
  "hr.employeeBankDetails": ["super_admin", "admin", "hr"],
  "hr.employeeDocuments": ["super_admin", "admin", "hr"],
  "hr.employeeDocuments.initialize": ["super_admin", "admin", "hr"],
  "hr.employeeDocuments.sendReminder": ["super_admin", "admin", "hr"],
  "hr.employeeDocuments.toggleRequired": ["super_admin", "admin", "hr"],
  "hr.employeeDocuments.verify": ["super_admin", "admin", "hr"],
  "hr.employeeEmergencyContacts": ["super_admin", "admin", "hr"],
  "hr.holidays": ["super_admin", "admin", "hr"],
  "hr.holidays.upload": ["super_admin", "admin", "hr"],
  "hr.leaveAccruals.run": ["super_admin", "admin", "hr"],
  "hr.leaveAccruals.runLog": ["super_admin", "admin", "hr"],
  "hr.leaveAccruals.yearEnd": ["super_admin", "admin", "hr"],
  "hr.leaveAdjustments": ["super_admin", "admin", "hr"],
  "hr.leaveBalances": ["super_admin", "admin", "hr", "executive"],
  "hr.leaveBalances.adjust": ["super_admin", "admin", "hr"],
  "hr.leaveBalances.bulkAdjust": ["super_admin", "admin", "hr"],
  "hr.leaveRequests": ["super_admin", "admin", "hr"],
  "hr.leaveRequests.myTeam": ["super_admin", "admin", "hr", "manager"],
  "hr.leaveRequests.review": ["super_admin", "admin", "hr", "manager"],
  "hr.leaveTypes": ["super_admin", "admin", "hr"],
  "hr.letterTemplates.roles": ["super_admin", "admin", "hr"],
  "hr.letterTemplates.sentences": ["super_admin", "admin", "hr"],
  "hr.letters": ["super_admin", "admin", "hr"],
  "hr.letters.approve": ["super_admin", "admin", "hr"],
  "hr.letters.download": ["super_admin", "admin", "hr"],
  "hr.letters.email": ["super_admin", "admin", "hr"],
  "hr.letters.issue": ["super_admin", "admin", "hr"],
  "hr.letters.reissue": ["super_admin", "admin", "hr"],
  "hr.letters.revoke": ["super_admin", "admin", "hr"],
  "hr.letters.wordingMatrix": ["super_admin", "admin", "hr"],
  "hr.myPlan": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "hr.newHire.onboardingStatus": ["super_admin", "admin", "hr", "operations", "manager"],
  "hr.planTemplates.delete": ["super_admin", "admin", "hr"],
  "hr.planTemplates.get": ["super_admin", "admin", "hr", "manager"],
  "hr.planTemplates.meta": ["super_admin", "admin", "hr", "manager"],
  "hr.planTemplates.patch": ["super_admin", "admin", "hr"],
  "hr.planTemplates.post": ["super_admin", "admin", "hr"],
  "hr.plans.acknowledge": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "hr.plans.get": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "hr.plans.goals": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "hr.plans.patch": ["super_admin", "admin", "hr", "manager"],
  "hr.plans.post": ["super_admin", "admin", "hr", "manager"],
  "hr.plans.weeklyUpdate": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "hr.policyAcknowledgements": ["super_admin", "admin", "hr", "manager"],
  "hr.reports.attendance": ["super_admin", "admin", "hr", "executive"],
  "hr.reports.salary.download": ["super_admin", "admin", "hr", "finance", "executive"],
  "hr.reports.salary.preview": ["super_admin", "admin", "hr", "finance", "executive"],
  "hr.reports.salary.recipients.get": ["super_admin", "admin", "hr", "finance", "executive"],
  "hr.reports.salary.recipients.put": ["super_admin", "admin", "hr"],
  "hr.reports.salary.runs": ["super_admin", "admin", "hr", "finance", "executive"],
  "hr.reports.salary.generate": ["super_admin", "admin", "executive"],
  "hr.reports.salary.adjust": ["super_admin", "admin", "executive"],
  "hr.reports.salary.approve": ["super_admin", "admin", "executive"],
  "hr.reports.salary.execute": ["super_admin", "admin", "hr", "executive"],
  "hr.salarySlips.generate": ["super_admin", "admin", "hr"],
  "hr.salarySlips.regenerate": ["super_admin", "admin", "hr"],
  "hr.shifts.currentTiming": ["super_admin", "admin", "hr", "manager"],
  "hr.tickets": ["super_admin", "admin", "hr"],
  "hr.tickets.review": ["super_admin", "admin", "hr"],
  "hr.tools.addendums.cancel": ["super_admin", "admin", "hr"],
  "hr.tools.addendums.countersign": ["super_admin", "admin", "hr"],
  "hr.tools.addendums.download": ["super_admin", "admin", "hr", "manager"],
  "hr.tools.addendums.send": ["super_admin", "admin", "hr"],
  "hr.tools.addendums.standalone.get": ["super_admin", "admin", "hr", "manager"],
  "hr.tools.addendums.standalone.post": ["super_admin", "admin", "hr"],
  "hr.tools.addendums.standalone.preview": ["super_admin", "admin", "hr", "manager"],
  "hr.tools.generateOfferLetter": ["super_admin", "admin", "hr", "manager"],
  "hr.tools.offerLetters": ["super_admin", "admin", "hr", "manager"],
  "hr.tools.offerLetters.addendums.cancel": ["super_admin", "admin", "hr"],
  "hr.tools.offerLetters.addendums.download": ["super_admin", "admin", "hr", "manager"],
  "hr.tools.offerLetters.addendums.get": ["super_admin", "admin", "hr", "manager"],
  "hr.tools.offerLetters.addendums.post": ["super_admin", "admin", "hr"],
  "hr.tools.offerLetters.addendums.send": ["super_admin", "admin", "hr"],
  "hr.tools.offerLetters.approve": ["super_admin", "admin"],
  "hr.tools.offerLetters.cancel": ["super_admin", "admin", "hr"],
  "hr.tools.offerLetters.reject": ["super_admin", "admin"],
  "hr.tools.offerLetters.startOnboarding": ["super_admin", "admin", "hr", "manager"],
  "hr.users": ["super_admin", "admin", "hr", "executive"],
  "hr.users.shift": ["super_admin", "admin", "hr"],
  "hr.users.shiftHistory": ["super_admin", "admin", "hr", "manager"],
  "onboarding.assignments": ["super_admin", "admin", "hr"],
  "onboarding.assignments.dueDate": ["super_admin", "admin", "hr"],
  "onboarding.assignments.exempt": ["super_admin", "admin", "hr"],
  "onboarding.assignments.grantException": ["super_admin", "admin", "hr"],
  "onboarding.extensionRequests": ["super_admin"],
  "onboarding.extensionRequests.pending": ["super_admin"],
  "onboarding.nightShiftConsents": ["super_admin", "admin", "hr", "executive"],
  "onboarding.policyCompliance": ["super_admin", "admin", "hr", "executive"],
  "onboarding.retroactiveAssignPolicies": ["super_admin", "admin", "hr"],
  "onboarding.sections": ["super_admin", "admin", "hr", "manager", "operations"],
  "onboarding.sections.quiz": ["super_admin", "admin", "hr", "manager", "operations"],
  "onboarding.seed": ["super_admin"],
  "onboarding.teamProgress": ["super_admin", "admin", "hr", "manager", "operations", "executive"],
  "onboarding.teamProgress.export.csv": ["super_admin", "admin", "hr", "manager", "operations", "executive"],
  "onboarding.tracks.assign": ["super_admin", "admin", "hr", "manager", "operations"],
  "onboarding.tracks.assignments": ["super_admin", "admin", "hr", "manager", "operations"],
  "onboarding.tracks.delete": ["super_admin", "admin", "hr"],
  "onboarding.tracks.patch": ["super_admin", "admin", "hr", "manager", "operations"],
  "onboarding.tracks.post": ["super_admin", "admin", "hr", "manager", "operations"],
  "onboarding.tracks.sections": ["super_admin", "admin", "hr", "manager", "operations"],
  "performance.checkIns.get": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.checkIns.patch": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.checkIns.post": ["super_admin", "admin", "hr", "manager"],
  "performance.employees": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.feedback": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.feedback.received": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.feedback.sent": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.goals": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.goals.batch": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.goals.checkIns": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.goals.milestones": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.goals.milestones.reorder": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.goals.team": ["super_admin", "admin", "hr", "manager"],
  "performance.milestones": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.reviewCycles.get": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.reviewCycles.patch": ["super_admin", "admin", "hr"],
  "performance.reviewCycles.post": ["super_admin", "admin", "hr"],
  "performance.reviews": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.reviews.manager": ["super_admin", "admin", "hr", "manager"],
  "performance.reviews.my": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.reviews.self": ["super_admin", "admin", "hr", "operations", "manager", "employee"],
  "performance.reviews.team": ["super_admin", "admin", "hr", "manager"],
  "performance.teamGoals": ["super_admin", "admin", "hr", "manager"],
  "rayoAcademy.assign": ["super_admin", "admin", "hr", "manager", "operations"],
  "rayoAcademy.provision": ["super_admin", "admin", "hr"],
  "rayoAcademy.teamProgress": ["super_admin", "admin", "hr", "manager", "operations"],
  // studio.* values reconciled to the exact effective role set each guard call
  // site grants today (auto-grant super_admin+admin baked in). Earlier values
  // here carried aspirational roles (e.g. content_manager — not a real role in
  // ACCESS_CONTROL_ROLES — and hr) that never took effect because the DB-driven
  // master flag is off; keeping the registry == live behavior preserves access.
  "studio.view": ["super_admin", "admin", "marketing_manager", "content_editor", "reviewer"],
  "studio.create_article": ["super_admin", "admin", "marketing_manager", "content_editor"],
  "studio.edit_article": ["super_admin", "admin", "marketing_manager", "content_editor"],
  "studio.generate_ai_draft": ["super_admin", "admin", "marketing_manager", "content_editor"],
  "studio.review_article": ["super_admin", "admin", "marketing_manager", "reviewer"],
  "studio.cm_review": ["super_admin", "admin", "hr", "content_manager"],
  "studio.marketing_approve": ["super_admin", "admin", "marketing_manager"],
  "studio.marketing_approve.bulk": ["super_admin", "admin"],
  "studio.schedule_publish": ["super_admin", "admin"],
  "studio.publish_article": ["super_admin"],
  "studio.manage_authors": ["super_admin", "admin"],
  "studio.manage_assets": ["super_admin", "admin", "marketing_manager", "content_editor"],
  "studio.view_analytics": ["super_admin", "admin", "marketing_manager"],
  "studio.manage_settings": ["super_admin", "admin"],
  "system.featureFlags": ["super_admin", "admin"],
  "sops.view": ["super_admin", "admin", "hr", "operations", "manager"],
  "sops.manage": ["super_admin", "admin", "hr", "operations", "manager"],
  "sops.rollout": ["super_admin", "admin"],
  "systemSettings": ["super_admin", "admin", "hr"],
  "helpDesk.create": ["super_admin", "admin", "hr", "finance", "operations", "manager", "recruiter", "employee"],
  "helpDesk.viewOwn": ["super_admin", "admin", "hr", "finance", "operations", "manager", "recruiter", "employee"],
  "helpDesk.viewTeam": ["super_admin", "admin", "hr", "operations", "manager"],
  "helpDesk.queue": ["super_admin", "admin", "hr", "operations"],
  "helpDesk.resolve": ["super_admin", "admin", "hr", "operations"],
  "helpDesk.approve": ["super_admin", "admin", "hr", "operations", "manager"],
  "salaryAdvance.create": ["super_admin", "admin", "hr", "finance", "operations", "manager", "recruiter", "employee"],
  "salaryAdvance.viewOwn": ["super_admin", "admin", "hr", "finance", "operations", "manager", "recruiter", "employee"],
  "salaryAdvance.managerApprove": ["super_admin", "admin", "hr", "manager"],
  "salaryAdvance.finalApprove": ["super_admin"],
  "salaryAdvance.accounts": ["super_admin", "admin", "hr", "finance"],
  "salaryAdvance.backfill": ["super_admin", "admin", "hr"],
  "salaryAdvance.policy.manage": ["super_admin", "admin", "hr"],
  "hr.salarySlips.view": ["super_admin", "admin", "hr", "finance"],
  "hr.salaryChanges.view": ["super_admin", "admin", "hr", "manager"],
  "hr.salaryChanges.manage": ["super_admin", "admin", "hr", "manager"],
  "hr.salaryChanges.approve": ["super_admin"],
  "hr.plans.attachOptions": ["super_admin", "admin", "hr", "manager"],
  "admin.releaseNotes": ["super_admin", "admin", "hr"],
  "admin.releaseNotes.gitLog": ["super_admin", "admin", "hr"],
  "admin.releaseNotes.generate": ["super_admin", "admin", "hr"],
  "admin.releaseNotes.combine": ["super_admin", "admin", "hr"],
  "admin.releaseNotes.submit": ["super_admin", "admin", "hr"],
  "admin.releaseNotes.approve": ["super_admin"],
  "admin.releaseNotes.reject": ["super_admin"],
  "admin.releaseNotes.send": ["super_admin"],
  "admin.studio.insightsLaunch.load": ["super_admin", "admin"],
  "admin.studio.insightsLaunch.announceAndRoute": ["super_admin", "admin"],
  "admin.studio.insightsLaunch.announce": ["super_admin", "admin"],
  "travel.quotes": ["super_admin", "admin", "hr", "operations", "manager", "recruiter", "employee"],
  "travel.quotes.approve": ["super_admin", "admin", "hr"],
  "travel.marginFloors": ["super_admin", "admin", "hr"],
};

// ============================================================================
// Studio Add-On Permission Grants
// ----------------------------------------------------------------------------
// Maps each Studio add-on level to the set of studio.* permission keys it
// grants. These are UNIONED with the user's role-based permissions at runtime.
// Final Publish (studio.publish_article) is intentionally absent from every
// add-on level — it remains super_admin only forever.
// ============================================================================

export const STUDIO_ADD_ON_PERMISSIONS: Record<string, string[]> = {
  marketing_manager: [
    "studio.view",
    "studio.create_article",
    "studio.edit_article",
    "studio.generate_ai_draft",
    "studio.manage_assets",
    "studio.review_article",
    "studio.marketing_approve",
    "studio.view_analytics",
  ],
  content_creator: [
    "studio.view",
    "studio.create_article",
    "studio.edit_article",
    "studio.generate_ai_draft",
    "studio.manage_assets",
    "studio.view_analytics",
  ],
  influencer: [
    "studio.view",
    "studio.create_article",
  ],
};

/**
 * Returns the Studio permission keys granted by a user's add-on level.
 * Returns an empty array if no add-on or unrecognised value.
 */
export function getStudioAddOnPermissions(addOn: string | null | undefined): string[] {
  if (!addOn) return [];
  return STUDIO_ADD_ON_PERMISSIONS[addOn] ?? [];
}

// ============================================================================
// Phase 2 — DB-driven live matrix
// ----------------------------------------------------------------------------
// The server hydrates an in-memory copy of the persisted (DB) matrix plus the
// master flag via `setLiveAccessMatrix`. `resolveRoles` consults that live
// matrix when the master flag is ON; otherwise it falls back to the Phase 1
// behavior (env flag -> config defaults, else call-site fallback). The shared
// module never touches the DB itself — it only holds the cache the server fills.
// ============================================================================

let liveMatrix: AccessRegistry | null = null;
let dbDrivenEnabled = false;

/** Settings keys used to persist the matrix and master flag. */
export const ACCESS_CONTROL_MATRIX_KEY = "access_control_matrix";
export const ACCESS_CONTROL_ENABLED_KEY = "access_control_db_enabled";

/** The role that can never be locked out of any feature. */
export const PROTECTED_ROLE = "super_admin";

/** Canonical, editable role universe for the Access Control grid. */
export const ACCESS_CONTROL_ROLES: { value: string; label: string }[] = [
  { value: "super_admin", label: "Super Admin" },
  { value: "admin", label: "Admin" },
  { value: "hr", label: "HR" },
  { value: "finance", label: "Finance" },
  { value: "operations", label: "Operations" },
  { value: "manager", label: "Manager" },
  { value: "recruiter", label: "Recruiter" },
  { value: "employee", label: "Employee" },
  { value: "executive", label: "Executive" },
  { value: "architect", label: "Architect" },
  { value: "marketing_manager", label: "Marketing Manager" },
  { value: "content_editor", label: "Content Editor" },
  { value: "reviewer", label: "Reviewer" },
];

/**
 * Hydrate / refresh the in-memory live matrix cache and master flag.
 * Called by the server on boot and after every save.
 */
export function setLiveAccessMatrix(matrix: AccessRegistry | null, enabled: boolean): void {
  liveMatrix = matrix;
  dbDrivenEnabled = enabled;
}

/** True when the DB-driven master flag is currently active. */
export function isDbDrivenAccessControl(): boolean {
  return dbDrivenEnabled && !!liveMatrix;
}

/**
 * The full effective feature -> roles matrix as the system currently resolves
 * it. When DB-driven, the live matrix is merged over the config defaults (so
 * keys absent from the DB still resolve). Otherwise the config defaults stand.
 */
export function getEffectiveMatrix(): AccessRegistry {
  if (dbDrivenEnabled && liveMatrix) {
    return { ...ACCESS_REGISTRY, ...liveMatrix };
  }
  return { ...ACCESS_REGISTRY };
}

/**
 * Resolve the allowed roles for a feature. The dynamic registry path is always
 * on (there is no longer a legacy flag).
 * DB-driven ON  -> live matrix entry (falling back to the registry default).
 * Otherwise     -> the registry default.
 * `defaultRoles` is a defensive seed used only if the key is absent from both;
 * in a correctly-seeded registry this never triggers.
 */
export function resolveRoles(featureKey: string, defaultRoles: string[]): string[] {
  if (dbDrivenEnabled && liveMatrix) {
    const entry = liveMatrix[featureKey] ?? ACCESS_REGISTRY[featureKey];
    if (entry) return entry;
  }
  return ACCESS_REGISTRY[featureKey] ?? defaultRoles;
}

/** True if `role` is permitted for `featureKey` (given the legacy fallback). */
export function isRoleAllowed(
  role: string | undefined | null,
  featureKey: string,
  fallbackRoles: string[],
): boolean {
  if (!role) return false;
  return resolveRoles(featureKey, fallbackRoles).includes(role);
}
