export const INDUSTRY_SPECIALTY_MAP: Record<string, string[]> = {
  Healthcare: [
    "Allied Health",
    "Cardiac Cath Lab",
    "Cardiac ICU",
    "Cardiology",
    "Cardiovascular",
    "Case Management",
    "Clinical",
    "CNO",
    "Critical Care",
    "CVOR",
    "Emergency Department",
    "ED",
    "ER",
    "Float Pool",
    "General Surgery",
    "Home Health",
    "Hospice",
    "ICU",
    "Imaging",
    "Infusion",
    "L&D",
    "Labor and Delivery",
    "Laboratory",
    "Long Term Care",
    "LTC",
    "Medical-Surgical",
    "Med/Surg",
    "Mental Health",
    "Neurology",
    "NICU",
    "Nursing",
    "Occupational Therapy",
    "Oncology",
    "Operating Room",
    "OR",
    "Orthopedics",
    "Pediatrics",
    "PICU",
    "Pharmacy",
    "Physical Therapy",
    "Progressive Care",
    "Psychiatric",
    "Radiology",
    "Rehab",
    "Respiratory Therapy",
    "RN",
    "SNF",
    "Skilled Nursing",
    "Speech Therapy",
    "Stepdown",
    "Surgical",
    "Telemetry",
    "Tele",
    "Travel Nurse",
    "Ultrasound",
    "Wound Care",
  ],
  IT: [
    ".NET",
    "Angular",
    "AWS",
    "Azure",
    "Backend",
    "Big Data",
    "Business Analyst",
    "Business Intelligence",
    "Cloud",
    "CRM",
    "Cybersecurity",
    "Data Analytics",
    "Data Engineer",
    "Data Science",
    "Database",
    "DevOps",
    "ERP",
    "Frontend",
    "Full Stack",
    "Hadoop",
    "Information Technology",
    "Infrastructure",
    "IT",
    "Java",
    "JavaScript",
    "Linux",
    "Machine Learning",
    "Mobile",
    "Network",
    "Node.js",
    "Oracle",
    "Power BI",
    "Project Manager",
    "Python",
    "QA",
    "React",
    "SAP",
    "Salesforce",
    "Scrum Master",
    "Security",
    "ServiceNow",
    "Software Engineer",
    "SQL",
    "System Administrator",
    "System Analyst",
    "Tableau",
    "Technical Writer",
    "UI/UX",
    "Web Developer",
    "Workday",
  ],
  Engineering: [
    "Aerospace",
    "Architecture",
    "AutoCAD",
    "Automation",
    "Chemical Engineering",
    "Civil Engineering",
    "Construction",
    "Design Engineer",
    "Electrical Engineering",
    "Environmental",
    "Field Engineer",
    "GIS",
    "HVAC",
    "Industrial Engineering",
    "Instrumentation",
    "Manufacturing",
    "Mechanical Engineering",
    "Plant Engineer",
    "Process Engineer",
    "Project Engineer",
    "Quality Engineer",
    "Reliability",
    "Structural Engineering",
    "Supply Chain",
  ],
  "Professional Services": [
    "Accounting",
    "Administrative",
    "Business Development",
    "Communications",
    "Compliance",
    "Consulting",
    "Customer Service",
    "Finance",
    "HR",
    "Human Resources",
    "Legal",
    "Management",
    "Marketing",
    "Office Management",
    "Operations",
    "Paralegal",
    "Payroll",
    "Procurement",
    "Program Manager",
    "Risk Management",
    "Sales",
    "Training",
  ],
};

export type Industry = keyof typeof INDUSTRY_SPECIALTY_MAP | "All";

export const INDUSTRIES: Industry[] = [
  "All",
  "Healthcare",
  "IT",
  "Engineering",
  "Professional Services",
];

export function getSpecialtiesForIndustry(industry: Industry): string[] | null {
  if (industry === "All") return null;
  return INDUSTRY_SPECIALTY_MAP[industry] ?? null;
}
